from flask import Flask, request, jsonify
from flask_cors import CORS
import yt_dlp
import os
import tempfile

app = Flask(__name__)
CORS(app)

@app.route('/')
def home():
    try:
        version = yt_dlp.version.__version__
    except:
        version = "unknown"
    return f"Power Smart Python Extractor is Running (yt-dlp: {version})"

import time

def _create_temp_cookie_file(cookie_string):
    """
    Converts a standard HTTP Cookie header string into a Netscape-format cookie file content
    and writes it to a temporary file. Returns the path to the temp file.
    """
    if not cookie_string:
        return None
    
    try:
        # Netscape format: domain, flag, path, secure, expiration, name, value
        # We assume .youtube.com for all, generic expiration (now + 1 year)
        lines = ["# Netscape HTTP Cookie File", "# This file was generated by Power Smart Backend"]
        expiration = int(time.time()) + 31536000 # +1 year
        
        # Split the cookie string "key=value; key2=value2"
        cookies = cookie_string.split(';')
        for cookie in cookies:
            parts = cookie.strip().split('=', 1)
            if len(parts) == 2:
                name, value = parts
                # .youtube.com	TRUE	/	TRUE	<exp>	<name>	<value>
                lines.append(f".youtube.com\tTRUE\t/\tTRUE\t{expiration}\t{name}\t{value}")
                # Also add google.com just in case
                lines.append(f".google.com\tTRUE\t/\tTRUE\t{expiration}\t{name}\t{value}")
        
        fd, path = tempfile.mkstemp(suffix='.txt', text=True)
        with os.fdopen(fd, 'w') as f:
            f.write('\n'.join(lines))
        
        return path
    except Exception as e:
        print(f"Error creating cookie file: {e}")
        return None

def extract_audio_url(video_url, custom_cookies=None, custom_ua=None, custom_po=None):
    # Fallback PO Token
    default_po = 'CgtPRDJlUFVKbmd4TSii79TKBjIKCgJQSxIEGgAgDGLfAgrcAjE0LllUPVFodXdvOFB6OUVkSHphMjI4VXBKbWsxX3lFT2xqN3NkRnBpcVBVZnZIN3hTaGcwZE1JUkgtMzRUY2VYSlFEcXBnV0J0X0haOWhLeVpTc2IzM1JNWU5GX0dEZjZOREpBdzRxQnpjQzNDVkFmTGRHQmJ2WmdTVzdPZl8yaHF1UnROVUNKTjRUYzZxeVVBd1FEOXNSMmMwR3NyTk15Y1F5TDdWdzl0RThCbktrV2J1TDRGdUFOcnRIWFFab0JObUxYQ09qTWY2aC1QTUFQc3haTTQ4WWxBZGFkLUVZSEJNdUJKYzlIamNYY1lCV1ZxTGY3TU5lX0YyN0tGQXBlRVQwaWJYQUhtbjZVVTgtYkJSNmxLUTNKaDViS1ZGakp2Z1RoZGlMNnlfY0xLdkZncmJfTjg5LUFOcHY3Y3J4cEluQlJweEw4QzAzcFpTZDk5eXRJeGpZeUplUQ%3D%3D'
    po_token = custom_po if custom_po else default_po

    ydl_opts = {
        'format': 'bestaudio/best',
        'quiet': True,
        'no_warnings': True,
        'http_headers': {
            'User-Agent': custom_ua if custom_ua else 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Referer': 'https://www.youtube.com/',
        },
        'extractor_args': {
            'youtube': {
                'player_client': ['ios', 'android', 'web_embedded'],
                'po_token': [f'web.gvs+{po_token}', f'mweb.gvs+{po_token}']
            }
        }
    }

    temp_cookie_path = None
    if custom_cookies:
        print(f"Received custom cookies: {custom_cookies[:50]}...") # Log masked
        temp_cookie_path = _create_temp_cookie_file(custom_cookies)
        if temp_cookie_path:
            ydl_opts['cookiefile'] = temp_cookie_path
            print(f"Created temp cookie file at {temp_cookie_path}")
    else:
        # Fallback to local cookies.txt
        cookie_file = os.path.join(os.path.dirname(__file__), 'cookies.txt')
        if os.path.exists(cookie_file):
            ydl_opts['cookiefile'] = cookie_file

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            return ydl.extract_info(video_url, download=False)
    except Exception as e:
        print(f"yt-dlp error: {e}")
        raise e
    finally:
        # Cleanup temp file
        if temp_cookie_path and os.path.exists(temp_cookie_path):
            try:
                os.remove(temp_cookie_path)
            except:
                pass

@app.route('/extract', methods=['GET'])
def extract_audio():
    video_id = request.args.get('id')
    if not video_id:
        return jsonify({"error": "Missing video ID"}), 400

    video_url = f"https://www.youtube.com/watch?v={video_id}"
    
    # Get cookies from request headers if the app sent them
    custom_cookies = request.headers.get('Cookie')
    custom_ua = request.headers.get('User-Agent')
    custom_po = request.headers.get('X-PO-Token')
    
    try:
        info = extract_audio_url(video_url, custom_cookies=custom_cookies, custom_ua=custom_ua, custom_po=custom_po)
        return jsonify({
            "stream_url": info.get('url'),
            "title": info.get('title'),
            "artist": info.get('uploader'),
            "duration": info.get('duration'),
            "thumbnail": info.get('thumbnail'),
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
